In [1]:
import pandas as pd
import pandas as pd
from graph_tool import Graph
from netpixi.data.gt import *
import netpixi

In [32]:
df = pd.read_csv("./champions/2015-16/champs.csv")

In [33]:
df

,Stage,Round,Group,Date,Team 1,FT,HT,Team 2,∑FT,ET,P,Comments
0,Qualifying,Qual. Round 1 | Leg 1,NaN,(Tue) 30 Jun 2015 (W26),Crusaders › NIR (1),0-0,0-0,Levadia › EST (1),NaN,NaN,NaN,NaN
1,Qualifying,Qual. Round 1 | Leg 1,NaN,(Tue) 30 Jun 2015 (W26),Lincoln Red Imps › GIB (1),0-0,0-0,FC Santa Coloma › AND (1),NaN,NaN,NaN,NaN
2,Qualifying,Qual. Round 1 | Leg 1,NaN,(Tue) 30 Jun 2015 (W26),Pyunik › ARM (1),2-1,0-0,S.S. Folgore Falciano Calcio › SMR (1),NaN,NaN,NaN,NaN
3,Qualifying,Qual. Round 1 | Leg 1,NaN,(Wed) 1 Jul 2015 (W26),B36 Torshavn › FRO (1),1-2,0-0,The New Saints › WAL (1),NaN,NaN,NaN,NaN
4,Qualifying,Qual. Round 1 | Leg 2,NaN,(Tue) 7 Jul 2015 (W27),Levadia › EST (2),1-1,0-0,Crusaders › NIR (2),(a) 1-1 (agg.),NaN,NaN,Away Goals (2)
...,...,...,...,...,...,...,...,...,...,...,...,...
212,Knockout,Semifinals | Leg 1,NaN,(Tue) 26 Apr 2016 (W17),Manchester City FC › ENG (11),0-0,0-0,Real Madrid CF › ESP (11),NaN,NaN,NaN,NaN
213,Knockout,Semifinals | Leg 1,NaN,(Wed) 27 Apr 2016 (W17),Atletico Madrid › ESP (11),1-0,1-0,Bayern München › GER (11),NaN,NaN,NaN,NaN
214,Knockout,Semifinals | Leg 2,NaN,(Tue) 3 May 2016 (W18),Bayern München › GER (12),2-1,1-0,Atletico Madrid › ESP (12),(a) 2-2 (agg.),NaN,NaN,Away Goals (2)
215,Knockout,Semifinals | Leg 2,NaN,(Wed) 4 May 2016 (W18),Real Madrid CF › ESP (12),1-0,1-0,Manchester City FC › ENG (12),1-0 (agg.),NaN,NaN,NaN
216,Knockout,Final,NaN,(Sat) 28 May 2016 (W21),Real Madrid CF › ESP (13),1-1 (*),1-0,Atletico Madrid › ESP (13),NaN,1-1 (a.e.t.),5-3 (pen.),NaN

In [43]:
def loading_data(data_dir):
    df = pd.read_csv(data_dir)
    df = df.loc[df["Stage"] != "Qualifying"]
    df = df.reset_index()
    team1 = []
    team2 = []
    for i in range(df.shape[0]):
        team1.append(df.iloc[i]["Team 1"].split("›")[0])
        team2.append(df.iloc[i]["Team 2"].split("›")[0])
    
    del df["Team 1"]
    del df["Team 2"]
    
    df["Team 1"] = team1
    df["Team 2"] = team2
    
    return df

df = loading_data("./champions/2015-16/champs.csv")
df

,index,Stage,Round,Group,Date,FT,HT,∑FT,ET,P,Comments,Team 1,Team 2
0,92,Group,Matchday ?,A,(Tue) 15 Sep 2015 (W37),2-0,1-0,NaN,NaN,NaN,NaN,Paris Saint-Germain,Malmo FF
1,93,Group,Matchday ?,A,(Tue) 15 Sep 2015 (W37),4-0,1-0,NaN,NaN,NaN,NaN,Real Madrid CF,Shakhtar Donetsk
2,94,Group,Matchday ?,B,(Tue) 15 Sep 2015 (W37),1-0,1-0,NaN,NaN,NaN,NaN,VfL Wolfsburg,CSKA Moskva
3,95,Group,Matchday ?,B,(Tue) 15 Sep 2015 (W37),2-1,1-1,NaN,NaN,NaN,NaN,PSV Eindhoven,Manchester United FC
4,96,Group,Matchday ?,C,(Tue) 15 Sep 2015 (W37),2-0,0-0,NaN,NaN,NaN,NaN,SL Benfica,Astana
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,212,Knockout,Semifinals | Leg 1,NaN,(Tue) 26 Apr 2016 (W17),0-0,0-0,NaN,NaN,NaN,NaN,Manchester City FC,Real Madrid CF
121,213,Knockout,Semifinals | Leg 1,NaN,(Wed) 27 Apr 2016 (W17),1-0,1-0,NaN,NaN,NaN,NaN,Atletico Madrid,Bayern München
122,214,Knockout,Semifinals | Leg 2,NaN,(Tue) 3 May 2016 (W18),2-1,1-0,(a) 2-2 (agg.),NaN,NaN,Away Goals (2),Bayern München,Atletico Madrid
123,215,Knockout,Semifinals | Leg 2,NaN,(Wed) 4 May 2016 (W18),1-0,1-0,1-0 (agg.),NaN,NaN,NaN,Real Madrid CF,Manchester City FC
124,216,Knockout,Final,NaN,(Sat) 28 May 2016 (W21),1-1 (*),1-0,NaN,1-1 (a.e.t.),5-3 (pen.),NaN,Real Madrid CF,Atletico Madrid